version: "3.7"
services:
  web:
    build:
      context: ./frontend
      target: serve
      args:
        VUE_APP_API_BASE: ${VUE_APP_API_BASE}
        VUE_APP_GMAP_KEY: ${VUE_APP_GMAP_KEY}
    command: nginx -g "daemon off;"
    ports:
      - "80:80"
  backend:
    build: ./backend
    command: "npm start"
    ports:
      - "8088:8088"
    environment:
      NODE_ENV: ${NODE_ENV}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      TTN_ID: ${TTN_ID}
      TTN_KEY: ${TTN_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}
    depends_on:
      - db
    links:
      - db:mysql
  db:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - yangtze-db:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
volumes:
  yangtze-db: